name: build dev apk
on:
  push:
jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
    - name: checkout project sources
      uses: actions/checkout@v3
      with:
        lfs: true
    - run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@v3
      with:
        path: app/build/outputs/apk/debug/*.apk
        name: obw.apk
